modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="bettershears2"
version="${file.jarVersion}"
displayName="BetterShears2"
logoFile="bettershears2.png"
authors="Yggdraszil"
description='''
Better Shears for 1.16.5
'''

[[dependencies.bettershears2]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bettershears2]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"